<?php

use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\HTML\HTMLHelper;

FormHelper::loadFieldClass('subform');

class JFormFieldSubformmore extends JFormFieldSubform
{

	protected $name = 'subformmore';


	protected $layout = 'subformmore';


	public function getLayoutPaths()
	{
		return array_merge([JPATH_ROOT . '/plugins/system/revo_optimizer/layouts/fields'], parent::getLayoutPaths());
	}


	public function getLayoutData()
	{
		return parent::getLayoutData(); // TODO: Change the autogenerated stub
	}


	public function getInput()
	{
		HTMLHelper::_('stylesheet', 'plg_system_revo_optimizer/subformmore.css', [
			'version' => filemtime(__FILE__),
			'relative' => true
		]);

		HTMLHelper::_('script', 'plg_system_revo_optimizer/subformmore.js', [
			'version' => filemtime(__FILE__),
			'relative' => true
		]);

		return parent::getInput(); // TODO: Change the autogenerated stub
	}


}