<?php

use Joomla\CMS\Factory;
use Joomla\CMS\Form\FormField;
use Joomla\CMS\HTML\HTMLHelper;

class JFormFieldSelectmenuitem extends FormField
{

	protected $name = 'selectmenuitem';


	protected $layout = 'selectmenuitem';


	public function getLayoutPaths()
	{
		return array_merge([JPATH_ROOT . '/plugins/system/revo_optimizer/layouts/fields'], parent::getLayoutPaths());
	}


	public function getLayoutData()
	{
		Factory::getLanguage()->load('com_modules');
		return parent::getLayoutData(); // TODO: Change the autogenerated stub
	}


	public function getInput()
	{

		HTMLHelper::_('stylesheet', 'plg_system_revo_optimizer/selectmenuitem.css', [
			'version' => filemtime(__FILE__),
			'relative' => true
		]);

		HTMLHelper::_('script', 'plg_system_revo_optimizer/selectmenuitem.js', [
			'version' => filemtime(__FILE__),
			'relative' => true
		]);

		return parent::getInput();
	}


}